version: '3'

services:
  app:
    container_name: app
    build: node
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh index.js
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    build: nginx
    container_name: nginx
    networks:
      - node-network
    ports: 
      - 8080:80
    depends_on:
      - app

  db: 
    build: mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge