version: '3'

services:
  app:
    container_name: app
    build: .
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
    command: node index.js
    depends_on:
      - db

  nginx:
    build: nginx
    container_name: nginx
    networks:
      - node-network
    ports: 
      - 8080:80
    depends_on:
      - app

  db: 
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge